name: Test Setup

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test environment
        run: |
          echo "Testing GitHub Actions setup"
          python --version
